#Convert the raw data into File(csv, excel, json)

In [1]:
import pandas as pd

In [2]:
#dictionary data first converted into tabular form then into any type of file.
Record = {
    "Roll no" : [221,222,223,224,225,226,227],
    "Name": ["Ali", "Sara", "Zainab", "Mahrosh", "Kinza", "Maham", "Rimsha"],
    "Maths" :[20, 30, 40, 50, 60, 70, 80],
    "Science":[25, 35, 45, 55, 65, 75, 85]
}
a=pd.DataFrame(Record)
a

   Roll no     Name  Maths  Science
0      221      Ali     20       25
1      222     Sara     30       35
2      223   Zainab     40       45
3      224  Mahrosh     50       55
4      225    Kinza     60       65
5      226    Maham     70       75
6      227   Rimsha     80       85

In [ ]:
#Code to change tabular data into any file:
a.to_excel("Record.xlsx", index=False)

In [4]:
#to read excel file
b = pd.read_excel("Record.xlsx")
b

   Roll no     Name  Maths  Science
0      221      Ali     20       25
1      222     Sara     30       35
2      223   Zainab     40       45
3      224  Mahrosh     50       55
4      225    Kinza     60       65
5      226    Maham     70       75
6      227   Rimsha     80       85

In [7]:
#to access specific raw data 
#.iloc[] -- position based
#.loc[] -- label based

b.iloc[2, 2]

np.int64(40)

In [9]:
b.iloc[3]

Roll no        224
Name       Mahrosh
Maths           50
Science         55
Name: 3, dtype: object

In [8]:
b.loc[1, "Science"]

np.int64(35)